version: '3'

services:
  web:
    build: .
    ports:
      - "8009:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - dbk
  dbk:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: prueba_konecta_db
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: